version: 2
jobs:
  build:
    docker:
      - image: circle/node:7.10

    working_directory: ~/repo

  steps: 
    - checkout

    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json"}}
          - vi-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json"}}
    
    - run: npm test